public interface ErrorMessage {
    String FILE_NOT_FOUND = "FILE NOT FOUND, PLEASE ENTER THE CORRECT FILE NAME";
    String WRONG_INCREMENT = "REQUESTED AMOUNT MUST BE IN 100 INCREMENTS";
    String VALUE_OUT_OF_BOUNDS = "REQUESTED AMOUNT OUT OF BOUNDS, MUST BE BETWEEN 1000 TO 15000";
    String MARKET_CSV_MISSING_NAME= "ERROR WITH MARKET CSV, NAME DOES NOT EXIST";
    String MARKET_CSV_WRONG_VALUE_TYPE = "ERROR WITH MARKET CSV, VALUE IS NOT NUMBER";
}
